FROM eclipse-temurin:17-jdk-jammy as build

WORKDIR /app

COPY gradlew .
COPY gradle gradle
COPY build.gradle* .
COPY settings.gradle* .

RUN chmod +x gradlew

RUN ./gradlew dependencies --no-daemon || true

COPY . .

RUN ./gradlew clean build -x test --no-daemon

# ---------------------------
# Runtime
# ---------------------------
FROM eclipse-temurin:17-jre-jammy

WORKDIR /app
COPY --from=build /app/build/libs/*.jar app.jar

EXPOSE 8080
ENTRYPOINT ["java", "-jar", "/app/app.jar"] 